name: Cyfrindev Deployment

on:
 push:
   branches: [main]

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
    - name: Setup SSH Agent
      run: |
        eval "$(ssh-agent -s)" 
        echo "Add SSH key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}"
        ssh-add -K <<< "${{ secrets.AWS_SSH_PRIVATE_KEY }}"

    - name: Run Remote/Artisan Commands
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.AWS_INSTANCE_IP }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/vhosts/cyfrindev-api
          git checkout main
          git pull 
          composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist
          php artisan migrate --force
          php artisan optimize
          php artisan queue:restart